### ISSUE TITLE
Any plans to support metadata generation based on DTO?

### ISSUE THREAD

**Issue by Dhana-Krishnasamy** [Breeze/breeze.server.java#1]
Any plans to support metadata generation based on DTOs as its done in .NET world? I dont want to tie my client code to the db.

Thanks

**Comment by steveschmitt** [comment]
You mean, using reflection to inspect the properties of the server-side domain model, and generate the metadata based on that?  It should work for data properties, but it's hard to get the cardinality right for navigation properties.

**Comment by Dhana-Krishnasamy** [comment]
No. I meant something like whats explained in this doc: http://www.breezejs.com/documentation/ef-design-tool

Basically If I generate a dummy hibernate config with required relationships, the framework should provide way to may my DTOs to Entities by hand, so when SaveChanges is called I can pluck data from DTO pass it to DB Entities. Or Is it already supported and I'm missing the docs?

**Comment by steveschmitt** [comment]
Sorry I didn't get back to you.  The server implementation has changed significantly since you asked this question.  Now saves are performed using a `SaveWorkState` object, which has methods `beforeSaveEntity`, `beforeSaveEntities`, and `beforeCommit`.  

Using the `beforeSaveEntities` method, you can intercept the save process and change your DTOs to Entities prior to save.  See the [SaveProcessor doc](http://breeze.github.io/doc-java-hib/save-processor.html) and the [SaveWorkState JavaDoc](http://breeze.github.io/doc-java-hib/api-docs/index.html?com/breeze/save/SaveWorkState.html) for more info.
